import bcrypt from 'bcryptjs';
export const data = {
  users: [
    {
      name: 'admin',
      email: 'admin@admin.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'user',
      email: 'user@user.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: 'Iphone 8 Plus',
      slug: 'iphone-8-plus',
      category: 'phones',
      image: '/images/p1.jpeg',
      price: 120,
      countInStock: 0,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality phone for professionals',
    },
    {
      // _id: '2',
      name: 'Iphone 11 Pro Max',
      slug: 'iphone-11-pro-max',
      category: 'phones',
      image: '/images/p2.jpeg',
      price: 250,
      countInStock: 20,
      brand: 'Apple',
      rating: 4.0,
      numReviews: 20,
      description: 'high quality phone for professionals',
    },
    {
      // _id: '3',
      name: 'Iphone 12 Pro Max',
      slug: 'iphone-12-pro-max',
      category: 'phones',
      image: '/images/p3.jpeg',
      price: 320,
      countInStock: 5,
      brand: 'Apple',
      rating: 3.5,
      numReviews: 40,
      description: 'high quality phone for professionals',
    },
    {
      // _id: '4',
      name: 'Iphone 13 Pro Max',
      slug: 'iphone-13-pro-max',
      category: 'phones',
      image: '/images/p4.jpeg',
      price: 420,
      countInStock: 15,
      brand: 'Apple',
      rating: 5.0,
      numReviews: 60,
      description: 'high quality phone for professionals',
    },
  ],
};
